/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'dob' : string,
  'nid' : string,
  'customerName' : string,
  'status' : string,
  'submittedAt' : bigint,
  'motherName' : string,
  'permanentAddress' : string,
  'district' : string,
  'fatherName' : string,
  'notes' : string,
  'phone' : string,
  'destinationCountry' : string,
  'presentAddress' : string,
  'purpose' : string,
  'refNumber' : string,
  'transactionId' : string,
}
export interface ContactConfig {
  'imo' : string,
  'establishYear' : string,
  'whatsapp' : string,
  'helpline' : string,
}
export interface PaymentConfig { 'nagad' : string, 'bkash' : string }
export interface Service {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'price' : number,
  'requirements' : string,
}
export interface _SERVICE {
  'addService' : ActorMethod<
    [string, string, string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteService' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAllServicesAdmin' : ActorMethod<
    [string],
    { 'ok' : Array<Service> } |
      { 'err' : string }
  >,
  'getApplicationByPhone' : ActorMethod<[string], Array<Application>>,
  'getApplicationByRef' : ActorMethod<[string], [] | [Application]>,
  'getApplications' : ActorMethod<
    [string],
    { 'ok' : Array<Application> } |
      { 'err' : string }
  >,
  'getContactConfig' : ActorMethod<[], ContactConfig>,
  'getPaymentConfig' : ActorMethod<[], PaymentConfig>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getStats' : ActorMethod<
    [string],
    {
        'ok' : {
          'total' : bigint,
          'pending' : bigint,
          'approved' : bigint,
          'rejected' : bigint,
          'processing' : bigint,
        }
      } |
      { 'err' : string }
  >,
  'logoutAdmin' : ActorMethod<[string], boolean>,
  'setContactConfig' : ActorMethod<
    [string, ContactConfig],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setPaymentConfig' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateApplicationStatus' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateService' : ActorMethod<
    [string, string, string, string, number, string, boolean],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'validateToken' : ActorMethod<[string], boolean>,
  'verifyAdmin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];