/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'price' : IDL.Float64,
  'requirements' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'nid' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'submittedAt' : IDL.Int,
  'motherName' : IDL.Text,
  'permanentAddress' : IDL.Text,
  'district' : IDL.Text,
  'fatherName' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'destinationCountry' : IDL.Text,
  'presentAddress' : IDL.Text,
  'purpose' : IDL.Text,
  'refNumber' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const ContactConfig = IDL.Record({
  'imo' : IDL.Text,
  'establishYear' : IDL.Text,
  'whatsapp' : IDL.Text,
  'helpline' : IDL.Text,
});
export const PaymentConfig = IDL.Record({
  'nagad' : IDL.Text,
  'bkash' : IDL.Text,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteService' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAllServicesAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Service), 'err' : IDL.Text })],
      [],
    ),
  'getApplicationByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
  'getApplicationByRef' : IDL.Func([IDL.Text], [IDL.Opt(Application)], []),
  'getApplications' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Application), 'err' : IDL.Text })],
      [],
    ),
  'getContactConfig' : IDL.Func([], [ContactConfig], []),
  'getPaymentConfig' : IDL.Func([], [PaymentConfig], []),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], []),
  'getStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'total' : IDL.Nat,
            'pending' : IDL.Nat,
            'approved' : IDL.Nat,
            'rejected' : IDL.Nat,
            'processing' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'logoutAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setContactConfig' : IDL.Func(
      [IDL.Text, ContactConfig],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setPaymentConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'validateToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'verifyAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'price' : IDL.Float64,
    'requirements' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'nid' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'submittedAt' : IDL.Int,
    'motherName' : IDL.Text,
    'permanentAddress' : IDL.Text,
    'district' : IDL.Text,
    'fatherName' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'destinationCountry' : IDL.Text,
    'presentAddress' : IDL.Text,
    'purpose' : IDL.Text,
    'refNumber' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const ContactConfig = IDL.Record({
    'imo' : IDL.Text,
    'establishYear' : IDL.Text,
    'whatsapp' : IDL.Text,
    'helpline' : IDL.Text,
  });
  const PaymentConfig = IDL.Record({ 'nagad' : IDL.Text, 'bkash' : IDL.Text });
  
  return IDL.Service({
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteService' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAllServicesAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Service), 'err' : IDL.Text })],
        [],
      ),
    'getApplicationByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
    'getApplicationByRef' : IDL.Func([IDL.Text], [IDL.Opt(Application)], []),
    'getApplications' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Application), 'err' : IDL.Text })],
        [],
      ),
    'getContactConfig' : IDL.Func([], [ContactConfig], []),
    'getPaymentConfig' : IDL.Func([], [PaymentConfig], []),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], []),
    'getStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'total' : IDL.Nat,
              'pending' : IDL.Nat,
              'approved' : IDL.Nat,
              'rejected' : IDL.Nat,
              'processing' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'logoutAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setContactConfig' : IDL.Func(
        [IDL.Text, ContactConfig],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setPaymentConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateService' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'validateToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };